name: 'Setup PureScript Yoga Stack'
description: 'Complete setup for PureScript Yoga packages with Bun, PureScript, and Spago'
branding:
  icon: 'package'
  color: 'purple'

inputs:
  purescript-version:
    description: 'PureScript compiler version (semver, "latest", or "unstable")'
    required: false
    default: '0.15.15'
  spago-version:
    description: 'Spago version (semver or "latest")'
    required: false
    default: 'latest'
  bun-version:
    description: 'Bun version'
    required: false
    default: 'latest'
  install-deps:
    description: 'Automatically run bun install'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Install PureScript compiler
      shell: bash
      run: bun install --global purescript@${{ inputs.purescript-version }}

    - name: Install Spago
      shell: bash
      run: bun install --global spago@${{ inputs.spago-version }}

    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: bun install
